# 01 Data Quality Audit

In [1]:
# khai báo thư viện
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
# Kiểm tra đường dẫn thư mục hiện tại
DATA_PATH = Path("../data/games.csv")
DATA_REDUCED_PATH = Path("../data/games_reduced.csv")
REPORT_PATH = Path("../reports/games_data_quality_audit.xlsx")

# Tạo thư mục reports nếu chưa tồn tại.
REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

print("Đường dẫn dữ liệu đang kiểm tra:", DATA_PATH.resolve())
print("Đường dẫn dữ liệu đã giảm:", DATA_REDUCED_PATH.resolve())
print("Đường dẫn báo cáo dự kiến:", REPORT_PATH.resolve())

if not DATA_PATH.exists():
    raise FileNotFoundError(
        "Không tìm thấy data/games.csv. "
        "Hãy kiểm tra cấu trúc thư mục hoặc điều chỉnh DATA_PATH."
    )

Đường dẫn dữ liệu đang kiểm tra: D:\VSCode\Games_Data_Science\data\games.csv
Đường dẫn dữ liệu đã giảm: D:\VSCode\Games_Data_Science\data\games_reduced.csv
Đường dẫn báo cáo dự kiến: D:\VSCode\Games_Data_Science\reports\games_data_quality_audit.xlsx

In [3]:
# Đọc file raw và kiểm tra số hàng cột
df_raw = pd.read_csv(DATA_REDUCED_PATH, encoding="utf-8", low_memory=False)

print("Đọc file thành công.")
print(f"Số dòng: {df_raw.shape[0]:,}")
print(f"Số cột: {df_raw.shape[1]:,}")
print(f"Kích thước dữ liệu: {df_raw.shape}")

display(df_raw.head())
display(df_raw.sample(min(5, len(df_raw)), random_state=42) if len(df_raw) else df_raw)

Đọc file thành công.
Số dòng: 8
Số cột: 26
Kích thước dữ liệu: (8, 26)

,id,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,Positive,...,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Windows,Mac,Linux
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,0,...,0,0,NaN,NaN,NaN,NaN,NaN,True,False,False
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,252,...,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",True,False,False
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,21,...,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",True,True,False
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,0,...,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,True,False,False
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,0,...,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,True,False,False

,id,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,Positive,...,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Windows,Mac,Linux
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,252,...,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",True,False,False
5,1654170,Agony VR,"Apr 5, 2023",0 - 20000,0,0,13.99,0,0,0,...,0,0,Ignibit,"Ignibit,Madmind Studio","Single-player,Tracked Controller Support,VR On...","Action,Adventure",NaN,True,False,False
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,0,...,0,0,NaN,NaN,NaN,NaN,NaN,True,False,False
7,700340,Galacatraz: Eject Equip Escape,"Feb 1, 2018",0 - 20000,0,0,0.99,0,0,0,...,0,0,Summer Bear Studio,Summer Bear Studio,"Single-player,Full controller support,Family S...","Action,Indie",NaN,True,False,False
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,21,...,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",True,True,False

In [4]:
# thông tin dataset raw
print("----- THÔNG TIN DATASET -----")
print("Số dòng:", len(df_raw))
print("Số cột:", len(df_raw.columns))
print("Tên cột:", df_raw.columns.tolist())
print("Dung lượng bộ nhớ (MB):",
      round(df_raw.memory_usage(deep=True).sum() / (1024 ** 2), 2))

df_raw.info()

----- THÔNG TIN DATASET -----
Số dòng: 8
Số cột: 26
Tên cột: ['id', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'Discount', 'DLC count', 'Positive', 'Negative', 'User score', 'Metacritic score', 'Recommendations', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Windows', 'Mac', 'Linux']
Dung lượng bộ nhớ (MB): 0.01
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          8 non-null      int64
 1   Name                        8 non-null      str
 2   Release date                8 non-null      str
 3   Estimated owners            8 non-null      str
 4   Peak CCU                    8 non-null      int64
 5   Required age                8 non-null      int64
 6   Price                       8 non-null      float64
 7   Discount                    8 non-null      int64
 8   DLC count                   8 non-null      int64
 9   Positive                    8 non-null      int64
 10  Negative                    8 non-null      int64
 11  User score                  8 non-null      int64
 12  Metacritic score            8 non-null      int64
 13  Recommendations             8 non-null      int64
 14  Average playtime forever    8 non-null      int64
 15  Average playtime two weeks  8 non-null      int64
 16  Median playtime forever     8 non-null      int64
 17  Median playtime two weeks   8 non-null      int64
 18  Developers                  7 non-null      str
 19  Publishers                  7 non-null      str
 20  Categories                  7 non-null      str
 21  Genres                      7 non-null      str
 22  Tags                        3 non-null      str
 23  Windows                     8 non-null      bool
 24  Mac                         8 non-null      bool
 25  Linux                       8 non-null      bool
dtypes: bool(3), float64(1), int64(14), str(8)
memory usage: 1.6 KB