# 01 Data Quality Audit

In [16]:
# khai báo thư viện
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [17]:
# Kiểm tra đường dẫn thư mục hiện tại
DATA_PATH = Path("../data/games.csv")
REPORT_PATH = Path("../reports/games_data_quality_audit.xlsx")

# Tạo thư mục reports nếu chưa tồn tại.
REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

print("Đường dẫn dữ liệu đang kiểm tra:", DATA_PATH.resolve())
print("Đường dẫn báo cáo dự kiến:", REPORT_PATH.resolve())

if not DATA_PATH.exists():
    raise FileNotFoundError(
        "Không tìm thấy data/games.csv. "
        "Hãy kiểm tra cấu trúc thư mục hoặc điều chỉnh DATA_PATH."
    )

Đường dẫn dữ liệu đang kiểm tra: D:\VSCode\Games_Data_Science\data\games.csv
Đường dẫn báo cáo dự kiến: D:\VSCode\Games_Data_Science\reports\games_data_quality_audit.xlsx

In [18]:
# Đọc file raw và kiểm tra số hàng cột
df_raw = pd.read_csv(DATA_PATH, encoding="utf-8", low_memory=False)

print("Đọc file thành công.")
print(f"Số dòng: {df_raw.shape[0]:,}")
print(f"Số cột: {df_raw.shape[1]:,}")
print(f"Kích thước dữ liệu: {df_raw.shape}")

display(df_raw.head())
display(df_raw.sample(min(5, len(df_raw)), random_state=42) if len(df_raw) else df_raw)

Đọc file thành công.
Số dòng: 8
Số cột: 39
Kích thước dữ liệu: (8, 39)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1654170,Agony VR,"Apr 5, 2023",0 - 20000,0,0,13.99,0,0,A JOURNEY THROUGH HELL! Explore the most terri...,"['English', 'French', 'Italian', 'German', 'Sp...",...,0,0,0,Ignibit,"Ignibit,Madmind Studio","Single-player,Tracked Controller Support,VR On...","Action,Adventure",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
700340,Galacatraz: Eject Equip Escape,"Feb 1, 2018",0 - 20000,0,0,0.99,0,0,"Years ago, Ricardo Luger was in the wrong plac...",['English'],...,0,0,0,Summer Bear Studio,Summer Bear Studio,"Single-player,Full controller support,Family S...","Action,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN

In [19]:
# thông tin dataset raw
print("----- THÔNG TIN DATASET -----")
print("Số dòng:", len(df_raw))
print("Số cột:", len(df_raw.columns))
print("Tên cột:", df_raw.columns.tolist())
print("Dung lượng bộ nhớ (MB):",
      round(df_raw.memory_usage(deep=True).sum() / (1024 ** 2), 2))

df_raw.info()

----- THÔNG TIN DATASET -----
Số dòng: 8
Số cột: 39
Tên cột: ['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DiscountDLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']
Dung lượng bộ nhớ (MB): 0.04
<class 'pandas.DataFrame'>
Index: 8 entries, 2539430 to 700340
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   AppID                       8 non-null      str
 1   Name                        8 non-null      str
 2   Release date                8 non-null      str
 3   Estimated owners            8 non-null      int64
 4   Peak CCU                    8 non-null      int64
 5   Required age                8 non-null      float64
 6   Price                       8 non-null      int64
 7   DiscountDLC count           8 non-null      int64
 8   About the game              7 non-null      str
 9   Supported languages         8 non-null      str
 10  Full audio languages        8 non-null      str
 11  Reviews                     0 non-null      float64
 12  Header image                8 non-null      str
 13  Website                     3 non-null      str
 14  Support url                 5 non-null      str
 15  Support email               7 non-null      str
 16  Windows                     8 non-null      bool
 17  Mac                         8 non-null      bool
 18  Linux                       8 non-null      bool
 19  Metacritic score            8 non-null      int64
 20  Metacritic url              0 non-null      float64
 21  User score                  8 non-null      int64
 22  Positive                    8 non-null      int64
 23  Negative                    8 non-null      int64
 24  Score rank                  0 non-null      float64
 25  Achievements                8 non-null      int64
 26  Recommendations             8 non-null      int64
 27  Notes                       2 non-null      str
 28  Average playtime forever    8 non-null      int64
 29  Average playtime two weeks  8 non-null      int64
 30  Median playtime forever     8 non-null      int64
 31  Median playtime two weeks   8 non-null      int64
 32  Developers                  7 non-null      str
 33  Publishers                  7 non-null      str
 34  Categories                  7 non-null      str
 35  Genres                      7 non-null      str
 36  Tags                        3 non-null      str
 37  Screenshots                 8 non-null      str
 38  Movies                      0 non-null      float64
dtypes: bool(3), float64(5), int64(14), str(17)
memory usage: 2.3 KB

In [20]:
# check missing values
overview = pd.DataFrame({
    "Column": df_raw.columns,
    "Data_Type": [str(df_raw[col].dtype) for col in df_raw.columns],
    "Non_Null_Count": [int(df_raw[col].notna().sum()) for col in df_raw.columns],
    "Missing_Count": [int(df_raw[col].isna().sum()) for col in df_raw.columns],
    "Missing_Rate_%": [
        round(float(df_raw[col].isna().mean() * 100), 2)
        for col in df_raw.columns
    ],
    "Unique_Values": [
        int(df_raw[col].nunique(dropna=True)) for col in df_raw.columns
    ],
    "Unique_Rate_%": [
        round(float(df_raw[col].nunique(dropna=True) / max(len(df_raw), 1) * 100), 2)
        for col in df_raw.columns
    ]
})

display(overview)

,Column,Data_Type,Non_Null_Count,Missing_Count,Missing_Rate_%,Unique_Values,Unique_Rate_%
0,AppID,str,8,0,0.0,8,100.0
1,Name,str,8,0,0.0,8,100.0
2,Release date,str,8,0,0.0,2,25.0
3,Estimated owners,int64,8,0,0.0,3,37.5
4,Peak CCU,int64,8,0,0.0,1,12.5
5,Required age,float64,8,0,0.0,7,87.5
6,Price,int64,8,0,0.0,3,37.5
7,DiscountDLC count,int64,8,0,0.0,2,25.0
8,About the game,str,7,1,12.5,7,87.5
9,Supported languages,str,8,0,0.0,5,62.5
10,Full audio languages,str,8,0,0.0,4,50.0
11,Reviews,float64,0,8,100.0,0,0.0
12,Header image,str,8,0,0.0,8,100.0
13,Website,str,3,5,62.5,3,37.5
14,Support url,str,5,3,37.5,5,62.5
15,Support email,str,7,1,12.5,7,87.5
16,Windows,bool,8,0,0.0,1,12.5
17,Mac,bool,8,0,0.0,2,25.0
18,Linux,bool,8,0,0.0,1,12.5
19,Metacritic score,int64,8,0,0.0,1,12.5
20,Metacritic url,float64,0,8,100.0,0,0.0
21,User score,int64,8,0,0.0,1,12.5
22,Positive,int64,8,0,0.0,4,50.0
23,Negative,int64,8,0,0.0,3,37.5
24,Score rank,float64,0,8,100.0,0,0.0
25,Achievements,int64,8,0,0.0,2,25.0
26,Recommendations,int64,8,0,0.0,3,37.5
27,Notes,str,2,6,75.0,2,25.0
28,Average playtime forever,int64,8,0,0.0,3,37.5
29,Average playtime two weeks,int64,8,0,0.0,1,12.5
30,Median playtime forever,int64,8,0,0.0,3,37.5
31,Median playtime two weeks,int64,8,0,0.0,1,12.5
32,Developers,str,7,1,12.5,7,87.5
33,Publishers,str,7,1,12.5,7,87.5
34,Categories,str,7,1,12.5,7,87.5
35,Genres,str,7,1,12.5,7,87.5
36,Tags,str,3,5,62.5,3,37.5
37,Screenshots,str,8,0,0.0,8,100.0
38,Movies,float64,0,8,100.0,0,0.0

In [21]:
missing_report = pd.DataFrame({
    "Missing_Count": df_raw.isna().sum(),
    "Missing_Rate_%": (df_raw.isna().mean() * 100).round(2)
})

missing_report["Review_Flag"] = np.select(
    [
        missing_report["Missing_Count"].eq(0),
        missing_report["Missing_Rate_%"].le(5),
        missing_report["Missing_Rate_%"].le(30)
    ],
    [
        "No pandas-recognized missing values",
        "Review: low missing rate",
        "Review: moderate missing rate"
    ],
    default="Review: high missing rate"
)

missing_report = missing_report.sort_values(
    "Missing_Rate_%", ascending=False
)

display(missing_report)

,Missing_Count,Missing_Rate_%,Review_Flag
Movies,8,100.0,Review: high missing rate
Metacritic url,8,100.0,Review: high missing rate
Reviews,8,100.0,Review: high missing rate
Score rank,8,100.0,Review: high missing rate
Notes,6,75.0,Review: high missing rate
Tags,5,62.5,Review: high missing rate
Website,5,62.5,Review: high missing rate
Support url,3,37.5,Review: high missing rate
Genres,1,12.5,Review: moderate missing rate
Developers,1,12.5,Review: moderate missing rate
Categories,1,12.5,Review: moderate missing rate
Support email,1,12.5,Review: moderate missing rate
About the game,1,12.5,Review: moderate missing rate
Publishers,1,12.5,Review: moderate missing rate
AppID,0,0.0,No pandas-recognized missing values
Price,0,0.0,No pandas-recognized missing values
Required age,0,0.0,No pandas-recognized missing values
Peak CCU,0,0.0,No pandas-recognized missing values
Estimated owners,0,0.0,No pandas-recognized missing values
Release date,0,0.0,No pandas-recognized missing values
Name,0,0.0,No pandas-recognized missing values
Full audio languages,0,0.0,No pandas-recognized missing values
Supported languages,0,0.0,No pandas-recognized missing values
Positive,0,0.0,No pandas-recognized missing values
User score,0,0.0,No pandas-recognized missing values
Metacritic score,0,0.0,No pandas-recognized missing values
Linux,0,0.0,No pandas-recognized missing values
Windows,0,0.0,No pandas-recognized missing values
Mac,0,0.0,No pandas-recognized missing values
DiscountDLC count,0,0.0,No pandas-recognized missing values
Header image,0,0.0,No pandas-recognized missing values
Median playtime forever,0,0.0,No pandas-recognized missing values
Average playtime two weeks,0,0.0,No pandas-recognized missing values
Average playtime forever,0,0.0,No pandas-recognized missing values
Recommendations,0,0.0,No pandas-recognized missing values
Negative,0,0.0,No pandas-recognized missing values
Achievements,0,0.0,No pandas-recognized missing values
Median playtime two weeks,0,0.0,No pandas-recognized missing values
Screenshots,0,0.0,No pandas-recognized missing values

In [22]:
# check for duplicates
duplicate_extra_count = int(df_raw.duplicated(keep="first").sum())
duplicate_all_mask = df_raw.duplicated(keep=False)
duplicate_involved_count = int(duplicate_all_mask.sum())

duplicate_summary = pd.DataFrame([{
    "Total_Rows": len(df_raw),
    "Duplicate_Extra_Rows": duplicate_extra_count,
    "Rows_Involved_In_Duplicate_Groups": duplicate_involved_count,
    "Duplicate_Extra_Rate_%": round(
        duplicate_extra_count / max(len(df_raw), 1) * 100, 2
    )
}])

print("Tóm tắt duplicate rows:")
display(duplicate_summary)

print("Ví dụ các dòng thuộc nhóm trùng hoàn toàn:")
display(df_raw.loc[duplicate_all_mask].head(20))

Tóm tắt duplicate rows:

,Total_Rows,Duplicate_Extra_Rows,Rows_Involved_In_Duplicate_Groups,Duplicate_Extra_Rate_%
0,8,0,0,0.0

Ví dụ các dòng thuộc nhóm trùng hoàn toàn:

Empty DataFrame
Columns: [AppID, Name, Release date, Estimated owners, Peak CCU, Required age, Price, DiscountDLC count, About the game, Supported languages, Full audio languages, Reviews, Header image, Website, Support url, Support email, Windows, Mac, Linux, Metacritic score, Metacritic url, User score, Positive, Negative, Score rank, Achievements, Recommendations, Notes, Average playtime forever, Average playtime two weeks, Median playtime forever, Median playtime two weeks, Developers, Publishers, Categories, Genres, Tags, Screenshots, Movies]
Index: []

[0 rows x 39 columns]

In [23]:
import warnings
warnings.filterwarnings("ignore")
 
try:
    display  # có sẵn trong Jupyter
except NameError:
    def display(x):
        print(x)
df_typed = df_raw.copy()
type_issues = []
 
for col in df_typed.select_dtypes(include="object").columns:
    s = df_typed[col].dropna().astype(str).str.strip()
    if s.empty:
        continue
 
    # Thử ép sang số (bỏ dấu phẩy, khoảng trắng, $, €, %)
    cleaned = s.str.replace(r"[,\s$€%]", "", regex=True)
    num = pd.to_numeric(cleaned, errors="coerce")
    if num.notna().mean() > 0.8:
        type_issues.append({
            "Column": col,
            "Suggested_Type": "numeric",
            "Parse_Rate": round(num.notna().mean(), 3),
            "Non_Convertible": s[num.isna()].unique()[:5].tolist(),
        })
        df_typed[col] = pd.to_numeric(
            df_typed[col].astype(str).str.strip()
            .str.replace(r"[,\s$€%]", "", regex=True),
            errors="coerce",
        )
        continue
 
    # Thử ép sang ngày tháng
    dt = pd.to_datetime(s, errors="coerce", dayfirst=True)
    if dt.notna().mean() > 0.8:
        type_issues.append({
            "Column": col,
            "Suggested_Type": "datetime",
            "Parse_Rate": round(dt.notna().mean(), 3),
            "Non_Convertible": s[dt.isna()].unique()[:5].tolist(),
        })
        df_typed[col] = pd.to_datetime(df_typed[col], errors="coerce", dayfirst=True)
 
print("\nCác cột bị đọc sai kiểu (đã thử ép sang df_typed):")
display(pd.DataFrame(type_issues))

Các cột bị đọc sai kiểu (đã thử ép sang df_typed):

  Column Suggested_Type  Parse_Rate Non_Convertible
0   Name       datetime         1.0              []

In [24]:
text_issues = []
for col in df_typed.select_dtypes(include="object").columns:
    s = df_typed[col].dropna().astype(str)
    if s.empty:
        continue
    text_issues.append({
        "Column": col,
        "Khoang_Trang_Thua": int((s != s.str.strip()).sum()),
        "Lan_Hoa_Thuong": int(s.nunique() - s.str.lower().str.strip().nunique()),
    })
 
print("\nĐịnh dạng text không nhất quán:")
display(pd.DataFrame(text_issues))

Định dạng text không nhất quán:

                  Column  Khoang_Trang_Thua  Lan_Hoa_Thuong
0                  AppID                  0               0
1           Release date                  0               0
2         About the game                  0               0
3    Supported languages                  0               0
4   Full audio languages                  0               0
5           Header image                  0               0
6                Website                  0               0
7            Support url                  0               0
8          Support email                  0               0
9                  Notes                  0               0
10            Developers                  0               0
11            Publishers                  0               0
12            Categories                  0               0
13                Genres                  0               0
14                  Tags                  0               0
15           Screenshots                  0               0

In [25]:
# outliers detection
numeric_cols = df_raw.select_dtypes(include="number").columns.tolist()
outlier_records = []
outlier_examples = {}

for col in numeric_cols:
    series = df_raw[col].dropna()

    # Bỏ qua cột không có giá trị hợp lệ để tính toán.
    if series.empty:
        continue

    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    mask = (
        df_raw[col].notna()
        & ((df_raw[col] < lower_bound) | (df_raw[col] > upper_bound))
    )

    outlier_records.append({
        "Column": col,
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound,
        "Outlier_Count": int(mask.sum()),
        "Outlier_Rate_%": round(float(mask.mean() * 100), 2),
        "IQR_Zero_Flag": bool(iqr == 0)
    })

    # Lưu một số ví dụ để điều tra, không xóa các dòng này.
    outlier_examples[col] = df_raw.loc[mask].head(10)

outlier_report = pd.DataFrame(outlier_records)
display(outlier_report)

# Xem ví dụ outlier của một cột bằng cách thay tên cột bên dưới:
# display(outlier_examples.get("column_name"))

,Column,Q1,Q3,IQR,Lower_Bound,Upper_Bound,Outlier_Count,Outlier_Rate_%,IQR_Zero_Flag
0,Estimated owners,0.00,0.25,0.25,-0.375,0.625,2,25.0,False
1,Peak CCU,0.00,0.00,0.00,0.000,0.000,0,0.0,True
2,Required age,3.99,10.24,6.25,-5.385,19.615,1,12.5,False
3,Price,0.00,2.50,2.50,-3.750,6.250,2,25.0,False
4,DiscountDLC count,0.00,0.25,0.25,-0.375,0.625,2,25.0,False
5,Metacritic score,0.00,0.00,0.00,0.000,0.000,0,0.0,True
6,User score,0.00,0.00,0.00,0.000,0.000,0,0.0,True
7,Positive,0.00,45.00,45.00,-67.500,112.500,2,25.0,False
8,Negative,0.00,3.00,3.00,-4.500,7.500,1,12.5,False
9,Achievements,0.00,0.00,0.00,0.000,0.000,1,12.5,True
10,Recommendations,0.00,26.75,26.75,-40.125,66.875,2,25.0,False
11,Average playtime forever,0.00,2.00,2.00,-3.000,5.000,2,25.0,False
12,Average playtime two weeks,0.00,0.00,0.00,0.000,0.000,0,0.0,True
13,Median playtime forever,0.00,2.00,2.00,-3.000,5.000,2,25.0,False
14,Median playtime two weeks,0.00,0.00,0.00,0.000,0.000,0,0.0,True

In [26]:
# kiểm tra các cột số


if numeric_cols:
    numeric_stats = df_raw[numeric_cols].describe(
        percentiles=[0.25, 0.50, 0.75]
    ).T

    numeric_stats["Missing_Count"] = df_raw[numeric_cols].isna().sum()
    numeric_stats["Zero_Count"] = df_raw[numeric_cols].eq(0).sum()
    numeric_stats["Negative_Count"] = df_raw[numeric_cols].lt(0).sum()
    numeric_stats["Skewness"] = df_raw[numeric_cols].skew().round(3)

    display(numeric_stats)
else:
    numeric_stats = pd.DataFrame()
    print("Dataset không có cột số được pandas nhận diện.")

,count,mean,std,min,25%,50%,75%,max,Missing_Count,Zero_Count,Negative_Count,Skewness
Estimated owners,8.0,1.1250,2.799872,0.0,0.00,0.000,0.25,8.00,0,6,0,2.746
Peak CCU,8.0,0.0000,0.000000,0.0,0.00,0.000,0.00,0.00,0,8,0,0.000
Required age,8.0,9.3975,11.610058,0.0,3.99,5.115,10.24,35.99,0,1,0,2.098
Price,8.0,9.3750,22.746664,0.0,0.00,0.000,2.50,65.00,0,6,0,2.705
DiscountDLC count,8.0,0.2500,0.462910,0.0,0.00,0.000,0.25,1.00,0,6,0,1.440
Reviews,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0,0,NaN
Metacritic score,8.0,0.0000,0.000000,0.0,0.00,0.000,0.00,0.00,0,8,0,0.000
Metacritic url,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0,0,NaN
User score,8.0,0.0000,0.000000,0.0,0.00,0.000,0.00,0.00,0,8,0,0.000
Positive,8.0,48.7500,91.512294,0.0,0.00,0.000,45.00,252.00,0,5,0,2.017
Negative,8.0,2.3750,4.501984,0.0,0.00,0.000,3.00,13.00,0,5,0,2.365
Score rank,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0,0,NaN
Achievements,8.0,2.3750,6.717514,0.0,0.00,0.000,0.00,19.00,0,7,0,2.828
Recommendations,8.0,42.2500,84.961756,0.0,0.00,0.000,26.75,231.00,0,6,0,2.032
Average playtime forever,8.0,85.3750,238.260924,0.0,0.00,0.000,2.00,675.00,0,6,0,2.828
Average playtime two weeks,8.0,0.0000,0.000000,0.0,0.00,0.000,0.00,0.00,0,8,0,0.000
Median playtime forever,8.0,157.6250,442.607190,0.0,0.00,0.000,2.00,1253.00,0,6,0,2.828
Median playtime two weeks,8.0,0.0000,0.000000,0.0,0.00,0.000,0.00,0.00,0,8,0,0.000
Movies,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0,0,NaN